storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    algorithm: bcrypt
    rounds: 10
    max_users: 1
security:
  api:
    legacy: true
    jwt:
      sign:
        algorithm: HS512
        issuer: komlankamekpo.pro
        expiresIn: 6m
      verify:
        algorithms:
          - HS512
        issuer: komlankamekpo.pro
    web:
      sign:
        algorithm: HS512
        issuer: komlankamekpo.pro
        expiresIn: 24h
      verify:
        algorithms:
          - HS512
        issuer: komlankamekpo.pro
server:
  keepAliveTimeout: 300
web:
  enable: true
  title: Private registry based on Verdaccio
  primary_color: "#291720"
  darkMode: True
listen:
  - 3000
middlewares:
  audit:
    enabled: true
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@*/*":
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  "**":
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
log: { type: stdout, format: pretty, level: http }